[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]

# [dependencies]
# solidity-rlp = { git = "https://github.com/hamdiallam/solidity-rlp", tag = "v2.0.8" }
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
